name: Update 3D Contributions

on:
  schedule:
    - cron: "0 12 * * *" 
  workflow_dispatch:       # Permite ejecución manual

jobs:
  build:
    permissions:
      contents: write 
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_3D }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_3D }}@github.com/${{ github.repository }}
          git add -A .
          git commit -m "Update 3D graph" || echo "No changes"
          git push
